site_name: DataScIIEnce
copyright: Copyright &copy; 2022 <b>DataScIIEnce</b>. All rights reserved<br> Machine & Deep learning association of <b>ENSIIE</b>
repo_name: Git repository
repo_url: https://github.com/DataScIIEnce-ENSIIE/datasciience-ensiie.github.io
edit_uri: edit/main/docs/
theme:
  custom_dir: overrides
  favicon: assets/img/logo_DS_transparent_alt.png
  logo: assets/img/logo_DS_transparent_alt.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - assets/style/extra.css

extra_javascript:
  - assets/scripts/extra.js

site_url: https://datasciience-ensiie.github.io
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DataScIIEnce-ENSIIE/
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datasciience
      name: LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/datasciience_club
      name: Instagram
    - icon: fontawesome/solid/envelope
      link: mailto:datasciience@gmail.com
      name: Official email address
    - icon: fontawesome/solid/compass
      link: https://datasciience.iiens.net/
      name: Official website

nav:
  - Home: "../"
  - Bureau: "../admin"
  - Sessions: "../sessions"
  - References: "../references"
  - Student pack: "../student-pack"
  - Guide: "../guide"
  - Contact: "../contact"
  - License: "../license"
  - English: "../english"
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
