# Main settings of the website

# Developer: Lucas RODRIGUEZ

# Project information
site_name: DataScIIEnce
site_url: https://datasciience-ensiie.github.io
site_author: DataScIIEnce
site_description: >-
  Data analisys, Machine and Deep learning student club of ENSIIE Paris

# Copyright
copyright: Copyright &copy; 2022 <b>DataScIIEnce</b>. All rights reserved<br> Machine & Deep learning association of <b>ENSIIE</b>

# Repository
repo_name: GitHub repository
repo_url: https://github.com/DataScIIEnce-ENSIIE/datasciience-ensiie.github.io

# Configuration
edit_uri: edit/main/docs/
theme:
  language: en
  custom_dir: overrides
  favicon: assets/img/logo_DS_transparent_alt.png
  logo: assets/img/logo_DS_transparent_alt.png
  icon:
    repo: fontawesome/solid/house
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - assets/style/extra.css

extra_javascript:
  - assets/scripts/extra.js
  - https://unpkg.com/leaflet@1.7.1/dist/leaflet.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DataScIIEnce-ENSIIE/
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datasciience
      name: LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/datasciience_club
      name: Instagram
    - icon: fontawesome/solid/envelope
      link: mailto:datasciience@gmail.com
      name: Official email address
    - icon: fontawesome/solid/compass
      link: https://datasciience.iiens.net/
      name: Official website
    - icon: fontawesome/solid/house
      link: https://www.ensiie.fr/
      name: School website

nav:
  - Home: "../"
  - About: "../about"
  - Getting started: "../guide"
  - Sessions: "../sessions"
  - Conferences: "../conferences"
  - References: "../references"
  - Useful links: "../links"
  - Contact: "../contact"
  - License: "../license"
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
